<a href="https://colab.research.google.com/github/MG2702/data-science-bootcamp/blob/main/NUMPY/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [6]:
import numpy as np

np.random.seed(42)
np.__version__

'1.19.5'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [11]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
C = np.concatenate((A,B), axis = 0)
C

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [19]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
np.concatenate((A, B), axis = 1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [20]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
np.concatenate((data, target), axis = 1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [21]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [28]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A1,A2,A3 = np.split(A, indices_or_sections=[2,6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[5 5 5 1]
 [1 1 3 1]
 [6 6 5 6]
 [4 1 6 4]
 [3 4 0 4]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [30]:
A = np.random.randint(low=0, high=2, size=(10, 6))
print(A)
np.count_nonzero(A)

[[1 1 0 0 0 1]
 [0 0 1 0 1 1]
 [1 0 0 0 0 0]
 [0 0 1 0 1 0]
 [0 0 1 1 1 1]
 [0 1 0 0 1 1]
 [1 1 1 1 1 1]
 [0 1 1 0 1 0]
 [0 1 0 0 0 0]
 [1 0 1 0 0 0]]


28

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [32]:
np.count_nonzero(A, axis=1)

array([3, 3, 1, 2, 4, 3, 6, 3, 1, 2])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [35]:
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
A

array([[-0.2647,  2.7202,  0.6257, -0.8572],
       [-1.0709,  0.4825, -0.2235,  0.714 ],
       [ 0.4732, -0.0728, -0.8468, -1.5148],
       [-0.4465,  0.8564,  0.2141, -1.2457],
       [ 0.1732,  0.3853, -0.8839,  0.1537],
       [ 0.0582, -1.143 ,  0.3578,  0.5608],
       [ 1.0831,  1.0538, -1.3777, -0.9378],
       [ 0.515 ,  0.5138,  0.515 ,  3.8527],
       [ 0.5709,  1.1356,  0.954 ,  0.6514],
       [-0.3153,  0.759 , -0.7728, -0.2368]])

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [38]:
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision=8, suppress=True)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [49]:
A = np.random.randn(8, 4)
np.delete(A, [2], 1)

array([[ 1.00629281, -0.57689187, -1.12970685],
       [ 0.52980418,  1.44156862, -0.79689526],
       [ 0.57707213, -0.20304539, -0.60398519],
       [ 0.08658979, -0.15567724,  0.25442084],
       [ 0.33760266, -0.41187697, -0.43255819],
       [ 0.39445214, -0.42098448,  2.0754008 ],
       [ 0.8711247 , -0.32602353, -0.40807537],
       [-2.03812454, -1.00808631, -0.35151348]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [50]:
v = np.array([3, 4, -2])
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [51]:
A = np.random.randint(10, size=(100, 30))
np.set_printoptions(edgeitems=10)
A

array([[6, 0, 8, 0, 0, 6, 1, 4, 7, 7, ..., 3, 0, 3, 6, 3, 5, 8, 0, 4, 6],
       [0, 3, 5, 1, 9, 4, 9, 0, 5, 5, ..., 3, 3, 9, 4, 3, 9, 7, 5, 5, 7],
       [6, 9, 9, 7, 1, 8, 0, 7, 3, 3, ..., 7, 8, 5, 6, 0, 4, 4, 9, 3, 5],
       [6, 8, 0, 5, 6, 2, 7, 4, 8, 4, ..., 9, 5, 1, 6, 1, 1, 0, 2, 5, 7],
       [8, 6, 3, 5, 4, 7, 0, 0, 5, 9, ..., 5, 7, 0, 6, 0, 6, 2, 7, 2, 0],
       [7, 2, 1, 0, 2, 1, 1, 5, 0, 1, ..., 2, 1, 0, 6, 6, 1, 6, 7, 0, 8],
       [6, 2, 7, 6, 7, 5, 8, 4, 2, 2, ..., 4, 6, 1, 6, 9, 6, 0, 6, 4, 2],
       [2, 3, 1, 1, 0, 4, 3, 9, 1, 2, ..., 3, 9, 5, 7, 0, 9, 7, 6, 0, 1],
       [2, 0, 8, 7, 1, 8, 6, 8, 5, 5, ..., 3, 8, 5, 1, 0, 4, 8, 5, 9, 6],
       [4, 9, 5, 4, 8, 5, 7, 1, 8, 4, ..., 4, 3, 2, 9, 4, 7, 3, 0, 6, 7],
       ...,
       [4, 3, 6, 9, 3, 1, 3, 7, 8, 2, ..., 3, 1, 7, 7, 9, 3, 2, 1, 8, 0],
       [6, 4, 7, 3, 6, 4, 4, 8, 8, 8, ..., 3, 2, 2, 5, 3, 5, 2, 3, 8, 4],
       [6, 9, 1, 4, 8, 2, 8, 5, 3, 6, ..., 1, 8, 0, 9, 5, 8, 0, 3, 3, 8],
       [4, 4, 5, 0, 0, 8, 