<a href="https://colab.research.google.com/github/MG2702/data-science-bootcamp/blob/main/NUMPY/071_080_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 71](#1)
* [Ćwiczenie 72](#2)
* [Ćwiczenie 73](#3)
* [Ćwiczenie 74](#4)
* [Ćwiczenie 75](#5)
* [Ćwiczenie 76](#6)
* [Ćwiczenie 77](#7)
* [Ćwiczenie 78](#8)
* [Ćwiczenie 79](#9)
* [Ćwiczenie 80](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.19.5'

### <a name='1'></a> Ćwiczenie 71
Podana jest poniższa tablica $A$:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Od drugiego wiersza tablicy $A$ przestaw losowo wiersze w tablicy.

__Wskazówka:__ Użyj funkcji _np.random.shuffle()_.


In [3]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['002', '4.99'],
       ['005', '1.49'],
       ['003', '7.99'],
       ['001', '14.99'],
       ['004', '2.49']], dtype='<U5')

### <a name='2'></a> Ćwiczenie 72
Podana jest poniższa tablica $A$:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Zwróć tablicę indeksów, które posortują tablicę $A$ rosnąco.

__Oczekiwny wynik:__


```
array([5, 2, 1, 0, 4, 3])
```
__Wskazówka:__ Użyj funkcji _np.argsort()_.



In [5]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
np.argsort(A)

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Ćwiczenie 73
Podana jest poniższa tablica $A$:

```
A = np.random.randn(10, 8)
```

Zaokrąglij wartości tej tablicy do trzeciego miejsca po przecinku.

__Wskazówka:__ Użyj funkcji _np.round()_.

In [8]:
A = np.random.randn(10, 8)
np.round(A,decimals=3)

array([[ 0.063,  0.502, -0.147,  0.181,  0.965, -1.065,  0.109,  0.106],
       [ 0.921, -0.227,  0.653,  1.103, -1.85 ,  1.169, -0.985, -1.094],
       [-2.879, -0.803, -0.005, -0.383, -0.463, -1.112,  0.867,  0.958],
       [ 0.418, -1.887,  2.273,  0.147,  0.54 , -1.498, -0.011,  0.413],
       [-0.141,  0.872,  1.3  , -1.344,  0.85 ,  0.394, -0.005, -1.571],
       [ 1.48 ,  0.397, -1.783, -0.243,  0.327,  0.507, -0.128,  0.342],
       [ 2.119,  1.547, -0.95 , -0.597, -0.111, -1.749, -1.341, -1.622],
       [-1.148,  1.39 , -0.855, -1.027,  0.883, -0.449,  0.419, -0.728],
       [-1.802,  0.468, -1.551, -0.51 , -0.733,  0.195, -0.556, -0.128],
       [-1.561,  2.   , -1.2  ,  1.201,  0.15 ,  0.141,  0.354, -1.88 ]])

### <a name='4'></a> Ćwiczenie 74
Wyznacz pierwiastki wielomianu:
* $W(x) = 4x^2 + 5x + 1$


__Wskazówka:__ Użyj funkcji _np.roots()_ oraz _np.polyval()_.

In [18]:
A = np.array([4, 5, 1])
np.roots(A)
X = np.polyval([4,5,1], -1)
Y = np.polyval([4,5,1], -0.25)
print(X, Y)

0 0.0


Dokonaj sprawdzenia.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='5'></a> Ćwiczenie 75
Wyznacz pierwiastki wielomianów:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Wskazówka:__ Użyj funkcji _np.roots()_.

In [19]:
Q = np.array([2,4,-5,1])
R = np.array([2,-5,1])
print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[2.28077641 0.21922359]


### <a name='6'></a> Ćwiczenie 76
Podane są wielomiany:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [20]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Wykonaj działania:
* $W(x) + Q(x)$

In [21]:
np.polyadd(W,Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [22]:
np.polysub(W,Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [23]:
np.polymul(W,Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [24]:
np.polyadd(W, 2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Ćwiczenie 77
Podana jest poniższa tablica:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Użyj funkcji znaku (_sign function_) dla tablicy $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Oczekiwany wynik:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Wskazówka:__ Użyj funkcji _np.sign()_.


In [25]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Ćwiczenie 78
Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:


```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```



In [27]:
np.arange(start='2021-01-01', stop='2021-02-01', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')


### <a name='9'></a> Ćwiczenie 79

Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:



```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```



In [29]:
A = np.arange(start='2021-01', stop='2022-01', dtype='datetime64[M]')
A.reshape(4,-1)

array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')

### <a name='10'></a> Ćwiczenie 80

Wykorzystując funkcję _np.datetime64()_ wygeneruj dzisiejszą datę (datę w chwili robienia ćwiczenia).

In [30]:
np.datetime64('today')

numpy.datetime64('2021-11-09')